In [4]:
import numpy as np
class MLP:
    def __init__(self,num_inputs=2,num_hidden=2,num_out=1,lr=0.1,y=0.5):
        input_weigh=[]
        inpu_hidd_weigh=[]
        hidd_out_weigh=[]
        self.num_input=num_inputs
        self.num_outputs=num_out
        self.num_hidden=num_hidden
        self.lr=lr
        self.y=y
        layers=self.num_input+self.num_hidden+self.num_outputs
        activation=0
        gradients=self.num_hidden+self.num_outputs
        for i in range(self.num_input):
            print("Enter the ",(i+1),"input weight")
            input_weigh.append(float(input()))
            input_weights=np.array(input_weigh)[np.newaxis]
        print(input_weights)
        for i in range(self.num_input):
            w=[]
            for j in range(self.num_hidden):
                print("Enter the middle",j,i,"weights")
                w.append(float(input()))
            inpu_hidd_weigh.append(w)
            inpu_hidd_weights=np.array(inpu_hidd_weigh)
        print(inpu_hidd_weights)
        for i in range(self.num_hidden):
            w=[]
            for j in range(self.num_outputs):
                print("Enter the output",j,i,"weights")
                w.append(float(input()))
                hidd_out_weigh.append(w)
                hidd_out_weights=np.array(hidd_out_weigh)
            print(hidd_out_weights)
       
       
        out_val=self.foward_pass(hidd_out_weights,input_weights, inpu_hidd_weights)
        print(out_val)
        update=self.backward_pass(out_val,y,hidd_out_weights,input_weights, inpu_hidd_weights)
        
    def sigmoid(self, s):
        return 1/(1 + np.exp(-s))
    
    
    def foward_pass(self,hidd_out_weights,input_weights, inpu_hidd_weights):
        self.hidden_value=np.dot(input_weights, inpu_hidd_weights)
        self.hid_v=np.array(self.sigmoid(self.hidden_value))
        self.output_value=np.dot(self.hid_v,hidd_out_weights)
        self.out_val=self.sigmoid(self.output_value)
        return self.out_val
    
    def backward_pass(self,out_val,y,hidd_out_weights,input_weights, inpu_hidd_weights):
        self.error=out_val-y
        self.err_delta=self.error*self.sig(out_val)

        self.hidd_error = np.dot(self.err_delta,hidd_out_weights.transpose())
        self.hidd_err_delta=self.hidd_error*self.sig(self.hid_v)
        
        self.hidden=np.dot(self.err_delta,hidd_out_weights.transpose())
        self.hidden_delta=self.hidden*self.sig(self.hid_v)
        
        inpu_hidd_weights-=np.dot(input_weights.transpose(),self.hidden_delta)
        
        print("The updated weights of input to hidden layers are")
        print(inpu_hidd_weights)
        hidd_out_weights-=np.dot(self.hid_v.transpose(),self.err_delta)
        print("The updated weights of hidden to output layers are")
        print(hidd_out_weights)
     
    def sig(self,s):
        return  s*(1-s)
MLP()
        
    

        

Enter the  1 input weight
0.35
Enter the  2 input weight
0.9
[[0.35 0.9 ]]
Enter the middle 0 0 weights
0.1
Enter the middle 1 0 weights
0.4
Enter the middle 0 1 weights
0.8
Enter the middle 1 1 weights
0.6
[[0.1 0.4]
 [0.8 0.6]]
Enter the output 0 0 weights
0.3
[[0.3]]
Enter the output 0 1 weights
0.9
[[0.3]
 [0.9]]
[[0.69028349]]
The updated weights of input to hidden layers are
[[0.09907093 0.39713992]
 [0.79761096 0.59264552]]
The updated weights of hidden to output layers are
[[0.27232597]
 [0.87299836]]
